#!/usr/bin/env node
// acharya-init.js — bootstrap the Acharya kit for the CURRENT project.
//
// Run AFTER .claude/acharya.config.json has been set for this project (the
// /acharya-init command writes it, or you edit it by hand). This script makes
// the kit match the config:
//
//   1. Prunes stack-specialist agents whose `requires` datastores aren't present
//      (and the matching slash-command, e.g. migration).
//   2. Wipes the inherited skills (.claude/skills/*) — they belong to the old
//      project and would mislead. Fresh skills are generated afterward by Guru
//      (skill-maintainer) — see the /acharya-init command.
//   3. Resets .claude/skills-routing.json to an empty template.
//   4. Reseeds .claude/.skills-sync to current git HEAD.
//
// Usage:
//   node .claude/scripts/acharya-init.js          # dry-run: print the plan
//   node .claude/scripts/acharya-init.js --apply   # actually mutate
//
// Always dry-run first. Core agents (no `requires`) are never pruned.

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const APPLY = process.argv.includes('--apply');
const CLAUDE_DIR = path.resolve(__dirname, '..');
const CONFIG_PATH = path.join(CLAUDE_DIR, 'acharya.config.json');
const AGENTS_DIR = path.join(CLAUDE_DIR, 'agents');
const COMMANDS_DIR = path.join(CLAUDE_DIR, 'commands');
const SKILLS_DIR = path.join(CLAUDE_DIR, 'skills');
const ROUTING_PATH = path.join(CLAUDE_DIR, 'skills-routing.json');
const SYNC_PATH = path.join(CLAUDE_DIR, '.skills-sync');

// Agent routing-id -> the slash-command that fronts it (pruned together).
const AGENT_COMMAND = { migration: 'migration' };

function die(msg) { console.error(`[acharya-init] ERROR: ${msg}`); process.exit(2); }
function log(msg) { process.stdout.write(msg + '\n'); }

if (!fs.existsSync(CONFIG_PATH)) die(`missing ${CONFIG_PATH} — set the project config first (or run /acharya-init).`);
let config;
try { config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8')); }
catch (e) { die(`acharya.config.json is not valid JSON: ${e.message}`); }

const datastores = (config.datastores || []).map(s => String(s).toLowerCase());
const agentDefs = config.agents || {};

log(`[acharya-init] project: ${(config.project && config.project.name) || '(unnamed)'}`);
log(`[acharya-init] datastores: ${datastores.join(', ') || '(none)'}`);
log(`[acharya-init] mode: ${APPLY ? 'APPLY (mutating)' : 'dry-run (no changes)'}`);
log('');

// 1. Decide which agents to prune.
const toPrune = [];
for (const [id, def] of Object.entries(agentDefs)) {
  const requires = (def && def.requires) || null;
  if (!requires) continue; // core agent — always keep
  const matches = requires.some(r => datastores.includes(String(r).toLowerCase()));
  if (!matches) toPrune.push(id);
}

log('## Agents');
const keep = Object.keys(agentDefs).filter(id => !toPrune.includes(id));
log(`keep (${keep.length}): ${keep.join(', ')}`);
log(`prune (${toPrune.length}): ${toPrune.join(', ') || '(none)'}`);
log('');

function rm(p) {
  if (!fs.existsSync(p)) return false;
  if (APPLY) fs.rmSync(p, { recursive: true, force: true });
  return true;
}

for (const id of toPrune) {
  const agentFile = path.join(AGENTS_DIR, `${id}.md`);
  if (rm(agentFile)) log(`  ${APPLY ? 'deleted' : 'would delete'} agents/${id}.md`);
  const cmd = AGENT_COMMAND[id];
  if (cmd) {
    const cmdFile = path.join(COMMANDS_DIR, `${cmd}.md`);
    if (rm(cmdFile)) log(`  ${APPLY ? 'deleted' : 'would delete'} commands/${cmd}.md`);
  }
}
log('');

// 2. Wipe inherited skills.
log('## Skills (inherited — will be regenerated by Guru)');
let skillNames = [];
if (fs.existsSync(SKILLS_DIR)) {
  skillNames = fs.readdirSync(SKILLS_DIR, { withFileTypes: true })
    .filter(d => d.isDirectory()).map(d => d.name);
}
if (skillNames.length) {
  log(`  ${APPLY ? 'deleting' : 'would delete'} ${skillNames.length} skill(s): ${skillNames.join(', ')}`);
  if (APPLY) for (const n of skillNames) fs.rmSync(path.join(SKILLS_DIR, n), { recursive: true, force: true });
} else {
  log('  (skills/ already empty)');
}
if (APPLY && !fs.existsSync(SKILLS_DIR)) fs.mkdirSync(SKILLS_DIR, { recursive: true });
log('');

// 3. Reset routing to an empty template.
log('## Routing');
const emptyRouting = {
  version: 1,
  _notes: [
    'Glob -> skill routing map. Read by .claude/scripts/affected-skills.js.',
    'Patterns are repo-root-relative. Supports ** (any depth) and * (single segment).',
    'Regenerated per-skill when Guru (skill-maintainer) creates skills. Add an entry per skill.'
  ],
  rules: []
};
if (APPLY) fs.writeFileSync(ROUTING_PATH, JSON.stringify(emptyRouting, null, 2) + '\n');
log(`  ${APPLY ? 'reset' : 'would reset'} skills-routing.json to empty template`);
log('');

// 4. Reseed sync marker to HEAD.
log('## Sync marker');
let head = '';
try { head = execSync('git rev-parse HEAD', { cwd: CLAUDE_DIR, encoding: 'utf8' }).trim(); } catch { /* no git */ }
if (head) {
  if (APPLY) fs.writeFileSync(SYNC_PATH, head + '\n');
  log(`  ${APPLY ? 'set' : 'would set'} .skills-sync = ${head}`);
} else {
  log('  (not a git repo — skipping .skills-sync reseed)');
}
log('');

log('## Next');
if (!APPLY) {
  log('  Dry-run only. Re-run with --apply to make these changes.');
} else {
  log('  Kit adapted. Now generate fresh skills for THIS project:');
  log('    -> have Guru (skill-maintainer) scan the codebase and create ONE skill per feature area.');
  log('    -> then rebuild skills-routing.json (one rule block per new skill).');
  log('  The /acharya-init command drives this automatically.');
}
